"""LLM provider abstraction with a deterministic mock fallback."""

from __future__ import annotations

import json
import re
import time
from dataclasses import dataclass

import httpx
from loguru import logger
from pydantic import BaseModel, ValidationError

from app.core.config import get_settings


@dataclass(slots=True)
class OutlineDraft:
    outline: list[dict[str, object]]
    text: str
    model_name: str


@dataclass(slots=True)
class ChapterDraft:
    content: str
    summary: str
    model_name: str


class OutlineItemPayload(BaseModel):
    """Validated outline item returned by the model."""

    chapter_number: int
    chapter_title: str
    goal: str


class OutlinePayload(BaseModel):
    """Validated outline payload returned by the model."""

    outline: list[OutlineItemPayload]


class ChapterPayload(BaseModel):
    """Validated chapter payload returned by the model."""

    content: str
    summary: str


class LLMService:
    """Generate outlines and chapters with provider fallback."""

    def __init__(self) -> None:
        self.settings = get_settings()

    def generate_outline(self, title: str, notes: str) -> OutlineDraft:
        """Generate a structured outline."""
        if self.settings.google_api_key:
            try:
                return self._generate_outline_google(title, notes)
            except Exception as exc:
                logger.warning("Google outline generation failed, falling back to mock: {}", exc)
        return self._generate_outline_mock(title, notes)

    def generate_chapter(
        self,
        *,
        title: str,
        chapter_title: str,
        chapter_number: int,
        outline_text: str,
        previous_summaries: str,
        chapter_notes: str | None,
        research_snippets: list[str],
    ) -> ChapterDraft:
        """Generate chapter prose and a summary for context chaining."""
        if self.settings.google_api_key:
            try:
                return self._generate_chapter_google(
                    title=title,
                    chapter_title=chapter_title,
                    chapter_number=chapter_number,
                    outline_text=outline_text,
                    previous_summaries=previous_summaries,
                    chapter_notes=chapter_notes,
                    research_snippets=research_snippets,
                )
            except Exception as exc:
                logger.warning("Google chapter generation failed, falling back to mock: {}", exc)
        return self._generate_chapter_mock(
            title=title,
            chapter_title=chapter_title,
            chapter_number=chapter_number,
            outline_text=outline_text,
            previous_summaries=previous_summaries,
            chapter_notes=chapter_notes,
            research_snippets=research_snippets,
        )

    def _generate_outline_mock(self, title: str, notes: str) -> OutlineDraft:
        outline = [
            {"chapter_number": 1, "chapter_title": f"Introduction to {title}", "goal": "Frame the topic."},
            {"chapter_number": 2, "chapter_title": "Core Systems and Practices", "goal": "Explain the operating model."},
            {"chapter_number": 3, "chapter_title": "Execution, Pitfalls, and Improvement", "goal": "Show how to apply the ideas."},
        ]
        text = "\n".join(
            f"{item['chapter_number']}. {item['chapter_title']} - {item['goal']}" for item in outline
        )
        text = f"Title: {title}\nEditor notes: {notes}\n\n{text}"
        return OutlineDraft(outline=outline, text=text, model_name="mock-llm")

    def _generate_chapter_mock(
        self,
        *,
        title: str,
        chapter_title: str,
        chapter_number: int,
        outline_text: str,
        previous_summaries: str,
        chapter_notes: str | None,
        research_snippets: list[str],
    ) -> ChapterDraft:
        snippets = "\n".join(f"- {snippet}" for snippet in research_snippets) or "- No external snippets"
        notes = chapter_notes or "No chapter revision notes supplied."
        previous = previous_summaries or "No previous chapters exist yet."
        content = (
            f"Chapter {chapter_number}: {chapter_title}\n\n"
            f"Book: {title}\n\n"
            f"Working outline context:\n{outline_text}\n\n"
            f"Previous chapter summaries:\n{previous}\n\n"
            f"Research snippets:\n{snippets}\n\n"
            f"Editor guidance: {notes}\n\n"
            "This draft demonstrates the workflow. In production, this section would be generated by the configured LLM provider. "
            "The content maintains continuity with prior summaries and stays aligned with the approved outline."
        )
        summary = (
            f"Chapter {chapter_number} summary: {chapter_title} establishes the main ideas for the topic and links them "
            "to the broader book narrative so later chapters can build on a compressed context chain."
        )
        return ChapterDraft(content=content, summary=summary, model_name="mock-llm")

    def _generate_outline_google(self, title: str, notes: str) -> OutlineDraft:
        prompt = self._outline_prompt(title, notes)
        data = self._call_google(prompt)
        payload = OutlinePayload.model_validate(data)
        outline = [item.model_dump() for item in payload.outline]
        text = "\n".join(
            f"{item['chapter_number']}. {item['chapter_title']} - {item['goal']}" for item in outline
        )
        return OutlineDraft(outline=outline, text=text, model_name=self.settings.google_model)

    def _generate_chapter_google(
        self,
        *,
        title: str,
        chapter_title: str,
        chapter_number: int,
        outline_text: str,
        previous_summaries: str,
        chapter_notes: str | None,
        research_snippets: list[str],
    ) -> ChapterDraft:
        snippets = "\n".join(research_snippets)
        prompt = self._chapter_prompt(
            title=title,
            chapter_title=chapter_title,
            chapter_number=chapter_number,
            outline_text=outline_text,
            previous_summaries=previous_summaries,
            chapter_notes=chapter_notes,
            snippets=snippets,
        )
        data = self._call_google(prompt)
        payload = ChapterPayload.model_validate(data)
        return ChapterDraft(
            content=payload.content,
            summary=payload.summary,
            model_name=self.settings.google_model,
        )

    def _call_google(self, prompt: str) -> dict[str, object]:
        payload = {
            "contents": [{"parts": [{"text": prompt}]}],
            "generationConfig": {
                "responseMimeType": "application/json",
                "temperature": 0.4,
            },
        }
        url = (
            f"{self.settings.google_base_url}/models/{self.settings.google_model}:generateContent"
            f"?key={self.settings.google_api_key}"
        )
        delay = self.settings.google_retry_delay_seconds
        last_error: Exception | None = None
        with httpx.Client(timeout=60.0) as client:
            for attempt in range(1, self.settings.google_max_retries + 1):
                try:
                    response = client.post(url, json=payload)
                    if response.status_code in {429, 500, 502, 503, 504}:
                        logger.warning(
                            "Google API transient error on attempt {} of {}: {} {}",
                            attempt,
                            self.settings.google_max_retries,
                            response.status_code,
                            response.text,
                        )
                        response.raise_for_status()
                    if response.is_error:
                        logger.error("Google API error {}: {}", response.status_code, response.text)
                        response.raise_for_status()
                    data = response.json()
                    break
                except httpx.HTTPStatusError as exc:
                    last_error = exc
                    if exc.response.status_code not in {429, 500, 502, 503, 504}:
                        raise
                    if attempt == self.settings.google_max_retries:
                        raise
                    time.sleep(delay)
                    delay *= 2
                except httpx.HTTPError as exc:
                    last_error = exc
                    if attempt == self.settings.google_max_retries:
                        raise
                    logger.warning(
                        "Google API transport error on attempt {} of {}: {}",
                        attempt,
                        self.settings.google_max_retries,
                        exc,
                    )
                    time.sleep(delay)
                    delay *= 2
            else:
                raise ValueError("Google API request failed without response") from last_error
        text = self._extract_google_text(data)
        logger.debug("Google model raw response text: {}", text)
        return self._parse_json_response(text)

    def _outline_prompt(self, title: str, notes: str) -> str:
        """Build a strict JSON-only prompt for outline generation."""
        return (
            "You are generating a book outline for an automated pipeline. "
            "Return ONLY valid JSON. Do not add explanations, markdown, bullets outside JSON, or code fences. "
            "The JSON must exactly match this schema: "
            '{"outline":[{"chapter_number":1,"chapter_title":"string","goal":"string"}]}. '
            "Generate 3 to 5 chapters. Chapter numbers must be sequential integers starting at 1. "
            f"Book title: {title}. Editor notes: {notes}"
        )

    def _chapter_prompt(
        self,
        *,
        title: str,
        chapter_title: str,
        chapter_number: int,
        outline_text: str,
        previous_summaries: str,
        chapter_notes: str | None,
        snippets: str,
    ) -> str:
        """Build a strict JSON-only prompt for chapter generation."""
        return (
            "You are generating one chapter for an automated book pipeline. "
            "Return ONLY valid JSON. Do not add explanations, markdown, bullets outside JSON, or code fences. "
            'The JSON must exactly match this schema: {"content":"string","summary":"string"}. '
            "The content field must contain the full chapter draft. The summary field must be a compact context summary for later chapters. "
            f"Book title: {title}. Chapter {chapter_number}: {chapter_title}. "
            f"Outline: {outline_text}. Previous summaries: {previous_summaries or 'None'}. "
            f"Editor notes: {chapter_notes or 'None'}. Research snippets: {snippets or 'None'}."
        )

    def _extract_google_text(self, data: dict[str, object]) -> str:
        """Extract the primary text block from a Google API response."""
        try:
            parts = data["candidates"][0]["content"]["parts"]
        except (KeyError, IndexError, TypeError) as exc:
            logger.error("Unexpected Google response shape: {}", data)
            raise ValueError("Unexpected Google response shape") from exc

        text_parts: list[str] = []
        fallback_parts: list[str] = []
        for part in parts:
            if not isinstance(part, dict):
                continue
            text = part.get("text")
            if not text:
                continue
            fallback_parts.append(str(text))
            if not part.get("thought"):
                text_parts.append(str(text))

        if text_parts:
            return "\n".join(text_parts)
        if fallback_parts:
            return "\n".join(fallback_parts)
        logger.error("Google response contained no text parts: {}", data)
        raise ValueError("Google response contained no text parts")

    def _parse_json_response(self, text: str) -> dict[str, object]:
        """Parse strict or embedded JSON from model output."""
        try:
            return json.loads(text)
        except json.JSONDecodeError:
            pass

        cleaned = text.strip()
        fenced = re.search(r"```(?:json)?\s*(\{.*\})\s*```", cleaned, re.DOTALL)
        if fenced:
            return json.loads(fenced.group(1))

        decoder = json.JSONDecoder()
        candidates: list[dict[str, object]] = []
        for match in re.finditer(r"\{", cleaned):
            try:
                parsed, _ = decoder.raw_decode(cleaned[match.start() :])
            except json.JSONDecodeError:
                continue
            if isinstance(parsed, dict):
                candidates.append(parsed)

        for candidate in candidates:
            if "outline" in candidate or {"content", "summary"}.issubset(candidate):
                return candidate

        if candidates:
            logger.error("Parsed JSON objects did not match expected schema: {}", candidates)
            self._validate_candidate_errors(candidates)
            raise ValueError("Model returned JSON with unexpected schema")

        logger.error("Model response did not contain JSON: {}", text)
        raise ValueError("Model response did not contain JSON")

    def _validate_candidate_errors(self, candidates: list[dict[str, object]]) -> None:
        """Log Pydantic validation failures for parsed JSON candidates."""
        for candidate in candidates:
            try:
                OutlinePayload.model_validate(candidate)
                return
            except ValidationError as outline_exc:
                try:
                    ChapterPayload.model_validate(candidate)
                    return
                except ValidationError as chapter_exc:
                    logger.error(
                        "Candidate failed outline validation: {} | chapter validation: {} | candidate: {}",
                        outline_exc,
                        chapter_exc,
                        candidate,
                    )
